### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by colinbes** [ghostm/lift-omniauth#37]
I apologize if I am having a totally blank moment but I am wanting to capture and display reason/cause of error. I see setting for omniauth.failureurl=/error but I, for the life of me, don't see how to filter/read the actual error. All I see is a redirect to omniauth.failureurl.

Much obliged.
Colin

**Comment by joescii** [comment]
Hi Colin!

I'm not sure how I missed this issue.  I know it has been a year since you opened it, so I suppose you figured out what you need?

**Comment by colinbes** [comment]
Ji Joe, no worries. I ended up not using omniauth (was no longer required) so didn't go any further.
Thanks for checking back.
Colin

**Comment by joescii** [comment]
No problem!
