### ISSUE TITLE
Google + scope problem

### ISSUE THREAD

**Issue by Hextar** [ghostm/lift-omniauth#49]
I'm not able to set the **scope**, neither using

omniauth.googlepermissions=userinfo.email
**OR**
omniauth.googlepermissions=email
**OR**
https://www.googleapis.com/auth/userinfo.email

I've noticed that in the file _GoogleProvider_, while doing _doGoogleSignin_, you added two times the line
    urlParameters += ("scope" -> googlePermissions)

May this is the cause?
Thanks

**Comment by joescii** [comment]
Perhaps.  I've never used the Google integration myself.  You can easily try this locally by changing the [`version` in `build.sbt`](https://github.com/ghostm/lift-omniauth/blob/master/build.sbt#L7) to `0.18-SNAPSHOT`, run `sbt publishLocal`, update your dependency version in your project to `0.18-SNAPSHOT`, and then run your project.

**Comment by eamocanu** [comment]
Hextar have you found a solution?

**Comment by ricsirigu** [comment]
This is the correct format

omniauth.googlepermissions=https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email
